### PR TITLE
Fix NameError for methods an object responds_to but doesn't have as a public_method

### PR DESCRIPTION
**Pull request by mattkimmel**
Hey Parker! Here's a quick fix I wrote for quacky that allows the verifier to pass an object if it responds_to an interface method, but the method isn't found by public_method. Previously, it would raise a NameError. I found this problem when trying to call delegated methods on a Draper object, but I imagine it's a common occurrence--it seems to happen for classes that make use of method_missing but override responds_to? instead of responds_to_missing?.

Let me know what you think.

### CODE REVIEW

**Comment by mattkimmel** [comment]
W/r/t the Travis failure, I had to up the rspec version in the gemspec to avoid that, which is kind of weird. I should have included that in the pull request.

**Comment by moonmaster9000** [comment]
Thanks Kimmel will check it out this evening when I get home!!!

**Comment by moonmaster9000** [comment]
Version 0.2.8. You're in the CHANGELOG!

**Comment by mattkimmel** [comment]
Woot! Thanks!

**Pull request merged**
